taxi_config:
  url: https://api.data.gov.sg/v1/transport/taxi-availability
  headers:
    Accept: application/vnd.geo+json
    Content-Type: application/json
  dim_table : dt_taxi
  data_table : ft_taxi
  region_table : dt_sg_region
postgre:
  host: localhost
  port: 5432
  database: taxi
  user: postgres
  password: rudianto